export const scenes = [
  {
    order: 1,
    slug: "scene-01",
    title: "Becoming Without End",
    ja: "経過のある街で",
    image: "/images/scene/scene-01.jpg",
    caption: "May, Aizuwakamatsu",
  },
  {
    order: 2,
    slug: "scene-02",
    title: "Where Light Decides",
    ja: "街灯が決める境界",
    image: "/images/scene/scene-02.jpg",
    caption: "April, Riverside",
  },
  {
    order: 3,
    slug: "scene-03",
    title: "Nothing Crosses Yet",
    ja: "隔たりのようなもの",
    image: "/images/scene/scene-03.jpg",
    caption: "March 2017, at a festival outside a U.S. military camp",
  },
  {
    order: 4,
    slug: "scene-04",
    title: "Between Bloom and Fall",
    ja: "咲くと散るあいだ",
    image: "/images/scene/scene-04.jpg",
    caption: "February, Saturday, park",
  },
  {
    order: 5,
    slug: "scene-05",
    title: "At the Edge of Sight",
    ja: "視界の端で",
    image: "/images/scene/scene-05.jpg",
    caption: "October, at a hideout",
  },
  {
    order: 6,
    slug: "scene-06",
    title: "A Day Off",
    ja: "休日",
    image: "/images/scene/scene-06.jpg",
    caption: "April, Sagamihara",
  },
  {
    order: 7,
    slug: "scene-07",
    title: "Slowly Coming Apart",
    ja: "灯台の近く",
    image: "/images/scene/scene-07.jpg",
    caption: "July, near a lighthouse",
  },
];